### ISSUE TITLE
mobcal.run list-directed I/O syntax error, unit 9

### ISSUE THREAD

**Issue by fschiro** [HopkinsLaboratory/MobCal-MPI#5]
Powerpoint says to use mpirun, but since the install did not work with OpenMPI, I had to use intel. And the only way to get it to run was ```mpiexec -n 4 ./MobCal-MPI_2.exe mobcal.run```

It gave error:
```bash
MobCal-MPI_2.exe mobcal.run                                                               forrtl: severe (59): list-directed I/O syntax error, unit 9, file D:\dev\work\pfizer\MobCal-MPI\GUI_Sample_Files\mfj    Image              PC                Routine            Line        Source                                              MobCal-MPI_2.exe   00007FF67C955423  Unknown               Unknown  Unknown                                             MobCal-MPI_2.exe   00007FF67C9548DA  Unknown               Unknown  Unknown                                             MobCal-MPI_2.exe   00007FF67C935F2C  Unknown               Unknown  Unknown                                             MobCal-MPI_2.exe   00007FF67C93153C  Unknown               Unknown  Unknown                                             MobCal-MPI_2.exe   00007FF67C9A72BB  Unknown               Unknown  Unknown                                             MobCal-MPI_2.exe   00007FF67C9A7700  Unknown               Unknown  Unknown                                             KERNEL32.DLL       00007FF97C727344  Unknown               Unknown  Unknown                                             ntdll.dll          00007FF97DDC26B1  Unknown               Unknown  Unknown 
```

I guess the powerpoint is not clear on mobcal.run file. It says it needs only two lines, <basename>.mfj and <basename>.mout, for each <basename>.mfj. 

So I created the file:

D:\dev\work\pfizer\MobCal-MPI\GUI_Sample_Files\mfj_creator\Mobcal_Inputs\GGG-H_tt_030_OptFreq.mfj
D:\dev\work\pfizer\MobCal-MPI\GUI_Sample_Files\mfj_creator\Mobcal_Inputs\GGG-H_tt_030_OptFreq.mout

Unsure how to get program to run now. 

`list-directed I/O syntax error, unit 9`

**Comment by fschiro** [comment]
This was an error on my part, closing.

**Comment by ChristianIeritano** [comment]
A full manual will be available in a few weeks. We apologize for the inconvenience, but it is a large document to put together!
